### ISSUE TITLE
CI randomly getting stuck in cmake-build pull-request

### ISSUE THREAD

**Issue by sezero** [libxmp/libxmp#462]
I made a rebased squashed branch out of #415 in my fork to test the CI issues:
It seems like CI randomly getting stuck, which did not happen before, and doesn't
happen with master branch: https://github.com/sezero/libxmp/tree/cmake-build

And with the latest rebase + force-push, even dist-package gets stuck.
Any insights on this?

https://github.com/sezero/libxmp/runs/3190626100 :
```
dist-package
Started 14m 4s ago
Can't find any online and idle self-hosted or hosted runner in the current repository, account/organization that matches the required labels: 'ubuntu-latest'
Waiting for a self-hosted or a hosted runner to pickup this job...
```

https://github.com/sezero/libxmp/runs/3190627636 :
```
windows-msys2-cmake (MINGW32, mingw-w64-i686-gcc mingw-w64-i686-cmake mingw-w64-i686-ninja)
Started 15m 4s ago
Can't find any online and idle self-hosted or hosted runner in the current repository, account/organization that matches the required labels: 'windows-latest'
Waiting for a self-hosted or a hosted runner to pickup this job...
```

https://github.com/sezero/libxmp/runs/3190627663 :
```
windows-msys2-cmake (MINGW64, mingw-w64-x86_64-gcc mingw-w64-x86_64-cmake mingw-w64-x86_64-ninja)
Started 15m 29s ago
Can't find any online and idle self-hosted or hosted runner in the current repository, account/organization that matches the required labels: 'windows-latest'
Waiting for a self-hosted or a hosted runner to pickup this job...
```

https://github.com/sezero/libxmp/runs/3190627590 :
```
MemorySanitizer
Started 15m 53s ago
Can't find any online and idle self-hosted or hosted runner in the current repository, account/organization that matches the required labels: 'ubuntu-latest'
Waiting for a self-hosted or a hosted runner to pickup this job...
```

https://github.com/sezero/libxmp/runs/3190627714 :
```
UndefinedBehaviorSanitizer
Started 16m 10s ago
Can't find any online and idle self-hosted or hosted runner in the current repository, account/organization that matches the required labels: 'ubuntu-latest'
Waiting for a self-hosted or a hosted runner to pickup this job...
```

**Comment by Wohlstand** [comment]
I bet this is GitHub's side temporary issue, it should go away as soon as possible.

**Comment by sezero** [comment]
The thing is, it hasn't happened with master branch, at least not yet.

If it's really github's problem: how do we report it?

**Comment by Wohlstand** [comment]
> If it's really github's problem: how do we report it?

You may just use the "Contact GitHub" form at the footer of the site. I do report some things and suggestions to them by that form

**Comment by sezero** [comment]
I thought it went away, but here we go again:
https://github.com/sezero/libxmp/runs/3191498858
https://github.com/sezero/libxmp/runs/3191498900
https://github.com/sezero/libxmp/runs/3191498923

**Comment by sezero** [comment]
Vitaly found this:
I found some: https://github.community/t/hosted-runners-not-picking-up-jobs/191663

**Comment by sezero** [comment]
Well, if someone knows how to report this (I don't), please do so, unless there
is some misconfiguration at our end.  The issue is still there.

**Comment by Wohlstand** [comment]
The fact it happen when we didn't change the build configuration at all, the last time (before applying your whitespace patch) I didn't change the build config for weeks, and the server had to use the version I made in the past week.

**Comment by sezero** [comment]
> The fact it happen when we didn't change the build configuration at all, the last time (before applying your whitespace patch) I didn't change the build config for weeks, and the server had to use the version I made in the past week.

It first showed itself with commit https://github.com/libxmp/libxmp/pull/415/commits/82c4e0d5f1a0f891b10f08c4e1130b77c0a5de56 in your PR branch

**Comment by Wohlstand** [comment]
> It first (I think) showed itself with commit 82c4e0d in your PR branch

This changed the build system config itself, but the CI builder got failed by itself even before launching any build scripts at all

**Comment by sezero** [comment]
@cmatsuoka (and @AliceLR ?), any advice?

**Comment by sezero** [comment]
I re-rebased my https://github.com/sezero/libxmp/tree/cmake-build fork, now it hasn't failed. This is maddening..

**Comment by AliceLR** [comment]
Not sure what's going on—the configuration looks right to me, but the error messages in the initial post imply it's trying to run on a self-hosted runner (as far as I know libxmp doesn't have *any* set up and you have to use `runs-on: self-hosted` explicitly to use them).

**Comment by AliceLR** [comment]
The [usage limit](https://docs.github.com/en/actions/reference/usage-limits-billing-and-administration#usage-limits) for free accounts is 20 concurrent jobs so adding so many new jobs might be getting the workflow run rate limited.

**Comment by Wohlstand** [comment]
> The clang and LTO cmake jobs can be culled too since they're only meant to test specific toolchain configurations and not the build system as a whole.

Maybe run two builds in one? I mean, sequentially do build CMake build, then run a build of Autotools, so, both building systems were verified in one task. Lemme try organize some...

**Comment by AliceLR** [comment]
> Maybe run two builds in one? I mean, sequentially do build CMake build, then run a build of Autotools, so, both building systems were verified in one task. Lemme try organize some...

No, I meant just get rid of them. They aren't testing anything the previous runs haven't already tested. The MSYS2 cmake runs can probably be dropped too.

**Comment by Wohlstand** [comment]
I meant making some sort of this:
```yml
  linux:
    strategy:
       matrix:
         distro: [ubuntu-latest, ubuntu-18.04]
    runs-on: ${{ matrix.distro }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run CMake script
        run: |
          mkdir build
          cmake . -DCMAKE_BUILD_TYPE=Debug -DWITH_UNIT_TESTS=ON -B build
      - name: Run CMake build
        run: |
          cmake --build build --target all
      - name: Run CMake checks
        run: |
          cd build
          ctest --output-on-failure
      - name: Create and run Autotools configure script
        run: |
          autoconf
          ./configure
      - name: Run Autotools build
        run: |
          make
      - name: Run Autotools check
        run: |
          make check
      - name: Run Autotools devcheck
        run: |
          (cd test-dev && autoconf && ./configure)
          make devcheck
```

I.e. do testing both build systems in the same task: first off running CMake build on the clear repository, then running Autotools once CMake build got tested. I added CMake tests to verify the case CMake gets built properly on all supported platforms too. You'll decrease coverage of CMake test if remove these completely.
